const fs       = require("fs");
const path     = require("path");
const archiver = require("archiver");
const { containerPathToHostRelative } = require("./fileService");
const { buildStoredFilename } = require("../utils/fileUtils");

// ─── Text Export ─────────────────────────────────────────────────────────────

/**
 * Build the formatted text export string for a song.
 *
 * @param {object} song  Full song object (with beats, completed_songs arrays)
 * @returns {string}
 */
function buildTextExport(song) {
  const line  = (char, len = 60) => char.repeat(len);
  const now   = new Date().toISOString().replace("T", " ").slice(0, 19);

  const beats          = Array.isArray(song.beats)          ? song.beats          : [];
  const completedSongs = Array.isArray(song.completed_songs) ? song.completed_songs : [];

  let out = "";

  out += `${"=".repeat(60)}\n`;
  out += `  BEATPAD SONG EXPORT\n`;
  out += `${"=".repeat(60)}\n\n`;

  out += `Title:        ${song.title || "(untitled)"}\n`;
  if (song.artist_name)   out += `Artist:       ${song.artist_name}\n`;
  if (song.status)        out += `Status:       ${song.status}\n`;
  if (song.mood)          out += `Mood:         ${song.mood}\n`;
  if (song.bpm)           out += `BPM:          ${song.bpm}\n`;
  if (song.key_signature) out += `Key:          ${song.key_signature}\n`;
  out += `\n`;

  // ── BEATS ────────────────────────────────────────────────────────────────
  out += `${line("-")}\n`;
  out += `  BEATS\n`;
  out += `${line("-")}\n`;
  if (beats.length === 0) {
    out += `  (no beats)\n`;
  } else {
    beats.forEach((b, i) => {
      out += `  [${i + 1}] ${b.file_name || b.original_video_title || "beat"}\n`;
      if (b.youtube_url)           out += `      Source:    ${b.youtube_url}\n`;
      if (b.hostRelativeFilePath)  out += `      File:      ${b.hostRelativeFilePath}\n`;
      if (b.file_size_bytes)       out += `      Size:      ${formatBytes(b.file_size_bytes)}\n`;
    });
  }
  out += `\n`;

  // ── COMPLETED SONGS ──────────────────────────────────────────────────────
  out += `${line("-")}\n`;
  out += `  COMPLETED SONGS\n`;
  out += `${line("-")}\n`;
  if (completedSongs.length === 0) {
    out += `  (no completed songs)\n`;
  } else {
    completedSongs.forEach((cs, i) => {
      const label = cs.version_label ? ` [${cs.version_label}]` : "";
      const primary = cs.is_primary ? " ★ PRIMARY" : "";
      out += `  [${i + 1}] ${cs.original_file_name}${label}${primary}\n`;
      if (cs.hostRelativeFilePath) out += `      File:      ${cs.hostRelativeFilePath}\n`;
      if (cs.file_size_bytes)      out += `      Size:      ${formatBytes(cs.file_size_bytes)}\n`;
      if (cs.notes)                out += `      Notes:     ${cs.notes}\n`;
    });
  }
  out += `\n`;

  // ── LYRICS ───────────────────────────────────────────────────────────────
  out += `${line("-")}\n`;
  out += `  LYRICS\n`;
  out += `${line("-")}\n`;
  if (song.lyrics && song.lyrics.trim()) {
    out += `\n${song.lyrics.trim()}\n\n`;
  } else {
    out += `  (no lyrics)\n\n`;
  }

  // ── NOTES ────────────────────────────────────────────────────────────────
  out += `${line("-")}\n`;
  out += `  NOTES\n`;
  out += `${line("-")}\n`;
  if (song.notes && song.notes.trim()) {
    out += `\n${song.notes.trim()}\n\n`;
  } else {
    out += `  (no notes)\n\n`;
  }

  // ── EXPORT DETAILS ───────────────────────────────────────────────────────
  out += `${line("=")}\n`;
  out += `  EXPORT DETAILS\n`;
  out += `${line("=")}\n`;
  out += `  Exported at: ${now} UTC\n`;
  out += `  Generated by BeatPad\n`;
  out += `${"=".repeat(60)}\n`;

  return out;
}

// ─── Package Preview ─────────────────────────────────────────────────────────

/**
 * Build a preview of what the ZIP package will contain.
 *
 * @param {object} song
 * @returns {{ song, beats, completedSongs, filesIncluded, warnings }}
 */
function buildPackagePreview(song) {
  const beats          = Array.isArray(song.beats)          ? song.beats          : [];
  const completedSongs = Array.isArray(song.completed_songs) ? song.completed_songs : [];
  const warnings       = [];
  const filesIncluded  = [];

  // Static text files always included
  filesIncluded.push({ type: "text",   fileName: "song-info.txt",   exists: true, hostRelativePath: null });
  filesIncluded.push({ type: "json",   fileName: "song-info.json",  exists: true, hostRelativePath: null });
  filesIncluded.push({ type: "text",   fileName: "lyrics.txt",      exists: true, hostRelativePath: null });
  filesIncluded.push({ type: "text",   fileName: "notes.txt",       exists: true, hostRelativePath: null });
  filesIncluded.push({ type: "text",   fileName: "README.txt",      exists: true, hostRelativePath: null });

  // Beats
  for (const beat of beats) {
    const exists = beat.file_path ? fs.existsSync(beat.file_path) : false;
    filesIncluded.push({
      type:             "beat",
      fileName:         `beats/${beat.file_name || "beat.wav"}`,
      exists,
      hostRelativePath: beat.hostRelativeFilePath || null,
    });
    if (!exists) {
      warnings.push(`Beat file not found on disk: ${beat.file_name}`);
    }
  }

  // Completed songs
  for (const cs of completedSongs) {
    const exists = cs.file_path ? fs.existsSync(cs.file_path) : false;
    filesIncluded.push({
      type:             "completed-song",
      fileName:         `completed-songs/${cs.stored_file_name || cs.original_file_name}`,
      exists,
      hostRelativePath: cs.hostRelativeFilePath || null,
    });
    if (!exists) {
      warnings.push(`Completed song file not found on disk: ${cs.original_file_name}`);
    }
  }

  return { song, beats, completedSongs, filesIncluded, warnings };
}

// ─── Zip Streaming ───────────────────────────────────────────────────────────

/**
 * Stream a ZIP package to the HTTP response.
 * Sets Content-Type and Content-Disposition headers before piping.
 *
 * @param {object}   song
 * @param {object}   res   Express response object
 */
function streamPackageZip(song, res) {
  const safeTitle = (song.title || "song")
    .replace(/[^a-zA-Z0-9 _-]/g, "")
    .replace(/\s+/g, "-")
    .slice(0, 80);

  const zipName = `${safeTitle}-package.zip`;

  res.setHeader("Content-Type",        "application/zip");
  res.setHeader("Content-Disposition", `attachment; filename="${zipName}"`);

  const archive = archiver("zip", { zlib: { level: 6 } });

  archive.on("error", (err) => {
    console.error("[exportService] archiver error:", err.message);
    // Headers already sent, just destroy the stream
    res.destroy(err);
  });

  archive.pipe(res);

  _appendZipContents(archive, song);

  archive.finalize();
}

/**
 * Save a ZIP package to the exports directory on disk.
 *
 * @param {object} song
 * @param {string} exportsDir  Container path to exports directory
 * @returns {Promise<{ fileName, containerPath, hostRelativePath }>}
 */
function savePackageZip(song, exportsDir) {
  return new Promise((resolve, reject) => {
    const safeTitle = (song.title || "song")
      .replace(/[^a-zA-Z0-9 _-]/g, "")
      .replace(/\s+/g, "-")
      .slice(0, 80);

    const now       = new Date();
    const pad       = (n) => String(n).padStart(2, "0");
    const timestamp =
      `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}` +
      `-${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`;

    const fileName      = `${safeTitle}-${timestamp}.zip`;
    const containerPath = path.join(exportsDir, fileName);

    // Ensure exports dir exists
    if (!fs.existsSync(exportsDir)) {
      fs.mkdirSync(exportsDir, { recursive: true });
    }

    const output  = fs.createWriteStream(containerPath);
    const archive = archiver("zip", { zlib: { level: 6 } });

    output.on("close", () => {
      resolve({
        fileName,
        containerPath,
        hostRelativePath: containerPathToHostRelative(containerPath),
      });
    });

    archive.on("error", (err) => reject(err));
    archive.pipe(output);

    _appendZipContents(archive, song);
    archive.finalize();
  });
}

// ─── Internal helpers ────────────────────────────────────────────────────────

/**
 * Append all content entries to an archiver instance.
 * Skips missing files with a console warning.
 */
function _appendZipContents(archive, song) {
  const beats          = Array.isArray(song.beats)          ? song.beats          : [];
  const completedSongs = Array.isArray(song.completed_songs) ? song.completed_songs : [];

  // song-info.txt
  archive.append(buildTextExport(song), { name: "song-info.txt" });

  // song-info.json
  const jsonPayload = JSON.stringify(
    {
      id:            song.id,
      title:         song.title,
      artist_name:   song.artist_name,
      mood:          song.mood,
      bpm:           song.bpm,
      key_signature: song.key_signature,
      status:        song.status,
      created_at:    song.created_at,
      updated_at:    song.updated_at,
      beats:         beats.map((b) => ({
        file_name:           b.file_name,
        youtube_url:         b.youtube_url,
        original_video_title: b.original_video_title,
        file_size_bytes:     b.file_size_bytes,
        created_at:          b.created_at,
      })),
      completed_songs: completedSongs.map((cs) => ({
        original_file_name: cs.original_file_name,
        version_label:      cs.version_label,
        notes:              cs.notes,
        is_primary:         cs.is_primary,
        file_size_bytes:    cs.file_size_bytes,
        created_at:         cs.created_at,
      })),
    },
    null,
    2
  );
  archive.append(jsonPayload, { name: "song-info.json" });

  // lyrics.txt
  archive.append(song.lyrics || "(no lyrics)", { name: "lyrics.txt" });

  // notes.txt
  archive.append(song.notes || "(no notes)", { name: "notes.txt" });

  // README.txt
  const readme =
    `BeatPad Song Package\n` +
    `====================\n\n` +
    `Song:   ${song.title || "(untitled)"}\n` +
    (song.artist_name ? `Artist: ${song.artist_name}\n` : "") +
    `\nContents:\n` +
    `  song-info.txt    — human-readable song details\n` +
    `  song-info.json   — machine-readable metadata\n` +
    `  lyrics.txt       — song lyrics\n` +
    `  notes.txt        — production notes\n` +
    `  beats/           — beat audio files\n` +
    `  completed-songs/ — finished song recordings\n\n` +
    `Generated by BeatPad on ${new Date().toISOString()}\n`;
  archive.append(readme, { name: "README.txt" });

  // Beat files
  for (const beat of beats) {
    if (!beat.file_path) continue;
    const resolved = path.resolve(beat.file_path);
    if (fs.existsSync(resolved)) {
      archive.file(resolved, { name: `beats/${beat.file_name || path.basename(resolved)}` });
    } else {
      console.warn(`[exportService] Beat file missing, skipping: ${beat.file_path}`);
    }
  }

  // Completed song files
  for (const cs of completedSongs) {
    if (!cs.file_path) continue;
    const resolved = path.resolve(cs.file_path);
    if (fs.existsSync(resolved)) {
      archive.file(resolved, {
        name: `completed-songs/${cs.stored_file_name || path.basename(resolved)}`,
      });
    } else {
      console.warn(`[exportService] Completed song file missing, skipping: ${cs.file_path}`);
    }
  }
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function formatBytes(bytes) {
  if (!bytes) return "unknown size";
  if (bytes < 1024)       return `${bytes} B`;
  if (bytes < 1048576)    return `${(bytes / 1024).toFixed(1)} KB`;
  if (bytes < 1073741824) return `${(bytes / 1048576).toFixed(1)} MB`;
  return `${(bytes / 1073741824).toFixed(2)} GB`;
}

module.exports = {
  buildTextExport,
  buildPackagePreview,
  streamPackageZip,
  savePackageZip,
};
